[package]
name = "lib-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
path = "lib.rs"


[features]
default=["dev"]
dev= []
prod=[]


[dependencies]
base64 = "0.22.1"
rusty_paseto = "0.7.1"


[lints]
workspace = true

[dev-dependencies]
anyhow = {workspace = true}
